version: "2"
run:
  modules-download-mode: readonly
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: all
  disable:
    - dupl
    - exhaustruct
    - tagliatelle
    - funcorder
  settings:
    cyclop:
      max-complexity: 12
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/weisshorn-cyd/gocti
            - github.com/go-viper/mapstructure/v2
            - github.com/kelseyhightower/envconfig
            - github.com/goccy/go-json
            - github.com/stretchr/testify
    funlen:
      lines: 99
      statements: 60
      ignore-comments: true
    gocognit:
      min-complexity: 50
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - generic
    nolintlint:
      require-explanation: true
      require-specific: true
    paralleltest:
      ignore-missing: true
    tagalign:
      sort: false
    usetesting:
      context-background: false
    varnamelen:
      ignore-names:
        - id
        - i
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
  exclusions:
    generated: disable
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        source: ^func Test
      - linters:
          - lll
        source: '`gocti.*`'
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/weisshorn-cyd/gocti)
        - blank
        - dot
  exclusions:
    generated: disable
    paths:
      - third_party$
      - builtin$
      - examples$
