run:
  modules-download-mode: readonly
  timeout: 2m

output:
  formats:
  - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  nolintlint:
    require-explanation: true
    require-specific: true
  gci:
    skip-generated: true
    sections:
      - standard
      - default
      - prefix(github.com/weisshorn-cyd/gocti)
      - blank
      - dot
  varnamelen:
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-names:
      - id
      - i # Iterator
  funlen:
    lines: 99
    statements: 60
    ignore-comments: true
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/weisshorn-cyd/gocti
          - github.com/go-viper/mapstructure/v2
          - github.com/kelseyhightower/envconfig
          - github.com/goccy/go-json
          - github.com/stretchr/testify
  cyclop:
    max-complexity: 12
    skip-tests: true
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic
  tagalign:
    sort: false
  paralleltest:
    ignore-missing: true
  gocognit:
    min-complexity: 50

linters:
  enable-all: true

  disable:
    - dupl
    - exhaustruct
    - exportloopref # Deprecated
    - tagliatelle

issues:
  exclude-rules:
    # disable funlen for test funcs
    - source: "^func Test"
      linters:
        - funlen
  exclude-generated: disable
