// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type Note struct {
	graphql.Note `gocti:",squash"`
}

//go:embed default_properties/note_default_properties.txt
var noteDefaultProperties string

func (n Note) DefaultProperties() string {
	return noteDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/note_list_query.txt
var noteListQueryString string

func (n Note) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		noteListQueryString,
		customAttributes,
	)
}

func (n Note) ListResponseField() string { return "notes" }

// Implementing the [api.ReadableEntity] interface.

func (n Note) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String) {
            note (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (n Note) ReadResponseField() string { return "note" }

// Implementing the [api.CreatableEntity] interface.

func (n Note) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: NoteAddInput!) {
            noteAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (n Note) CreateResponseField() string { return "noteAdd" }

// NoteAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type NoteAddInput struct {
	// NoteAddInput
	StixID             string     `gocti:"stix_id"               json:"stix_id,omitempty"`
	XOpenctiStixIDs    []string   `gocti:"x_opencti_stix_ids"    json:"x_opencti_stix_ids,omitempty"`
	AttributeAbstract  string     `gocti:"attribute_abstract"    json:"attribute_abstract,omitempty"`
	Content            string     `gocti:"content"               json:"content,omitempty"`
	Authors            []string   `gocti:"authors"               json:"authors,omitempty"`
	NoteTypes          []string   `gocti:"note_types"            json:"note_types,omitempty"`
	Likelihood         int        `gocti:"likelihood"            json:"likelihood,omitempty"`
	Revoked            bool       `gocti:"revoked"               json:"revoked,omitempty"`
	Lang               string     `gocti:"lang"                  json:"lang,omitempty"`
	CreatedBy          string     `gocti:"createdBy"             json:"createdBy,omitempty"`
	Confidence         int        `gocti:"confidence"            json:"confidence,omitempty"`
	ObjectMarking      []string   `gocti:"objectMarking"         json:"objectMarking,omitempty"`
	ObjectLabel        []string   `gocti:"objectLabel"           json:"objectLabel,omitempty"`
	ObjectOrganization []string   `gocti:"objectOrganization"    json:"objectOrganization,omitempty"`
	ExternalReferences []string   `gocti:"externalReferences"    json:"externalReferences,omitempty"`
	Objects            []string   `gocti:"objects"               json:"objects,omitempty"`
	Created            *time.Time `gocti:"created"               json:"created,omitempty"`
	Modified           *time.Time `gocti:"modified"              json:"modified,omitempty"`
	XOpenctiWorkflowID string     `gocti:"x_opencti_workflow_id" json:"x_opencti_workflow_id,omitempty"`
	ClientMutationID   string     `gocti:"clientMutationId"      json:"clientMutationId,omitempty"`
	Update             bool       `gocti:"update"                json:"update,omitempty"`
	File               []byte     `gocti:"file"                  json:"file,omitempty"`
}

func (input NoteAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (n Note) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                noteEdit (id: $id) {
                    delete
                }
            }`
}

func (n Note) DeleteResponseField() string { return "noteEdit" }
