// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type Grouping struct {
	graphql.Grouping `gocti:",squash"`
}

//go:embed default_properties/grouping_default_properties.txt
var groupingDefaultProperties string

func (g Grouping) DefaultProperties() string {
	return groupingDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/grouping_list_query.txt
var groupingListQueryString string

func (g Grouping) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		groupingListQueryString,
		customAttributes,
	)
}

func (g Grouping) ListResponseField() string { return "groupings" }

// Implementing the [api.ReadableEntity] interface.

func (g Grouping) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String!) {
            grouping (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (g Grouping) ReadResponseField() string { return "grouping" }

// Implementing the [api.CreatableEntity] interface.

func (g Grouping) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: GroupingAddInput!) {
            groupingAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (g Grouping) CreateResponseField() string { return "groupingAdd" }

// GroupingAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type GroupingAddInput struct {
	// GroupingAddInput
	StixID             string                      `gocti:"stix_id"               json:"stix_id,omitempty"`
	XOpenctiStixIDs    []string                    `gocti:"x_opencti_stix_ids"    json:"x_opencti_stix_ids,omitempty"`
	Name               string                      `gocti:"name"                  json:"name,omitempty"`
	Description        string                      `gocti:"description"           json:"description,omitempty"`
	Content            string                      `gocti:"content"               json:"content,omitempty"`
	ContentMapping     string                      `gocti:"content_mapping"       json:"content_mapping,omitempty"`
	Context            graphql.GroupingContext     `gocti:"context"               json:"context,omitempty"`
	XOpenctiAliases    []string                    `gocti:"x_opencti_aliases"     json:"x_opencti_aliases,omitempty"`
	Revoked            bool                        `gocti:"revoked"               json:"revoked,omitempty"`
	Lang               string                      `gocti:"lang"                  json:"lang,omitempty"`
	Confidence         int                         `gocti:"confidence"            json:"confidence,omitempty"`
	CreatedBy          string                      `gocti:"createdBy"             json:"createdBy,omitempty"`
	ObjectMarking      []string                    `gocti:"objectMarking"         json:"objectMarking,omitempty"`
	ObjectLabel        []string                    `gocti:"objectLabel"           json:"objectLabel,omitempty"`
	ObjectOrganization []string                    `gocti:"objectOrganization"    json:"objectOrganization,omitempty"`
	ExternalReferences []string                    `gocti:"externalReferences"    json:"externalReferences,omitempty"`
	Objects            []string                    `gocti:"objects"               json:"objects,omitempty"`
	Created            *time.Time                  `gocti:"created"               json:"created,omitempty"`
	Modified           *time.Time                  `gocti:"modified"              json:"modified,omitempty"`
	ClientMutationID   string                      `gocti:"clientMutationId"      json:"clientMutationId,omitempty"`
	XOpenctiWorkflowID string                      `gocti:"x_opencti_workflow_id" json:"x_opencti_workflow_id,omitempty"`
	Update             bool                        `gocti:"update"                json:"update,omitempty"`
	File               []byte                      `gocti:"file"                  json:"file,omitempty"`
	AuthorizedMembers  []graphql.MemberAccessInput `gocti:"authorized_members"    json:"authorized_members,omitempty"`
}

func (input GroupingAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (g Grouping) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                groupingDelete (id: $id)
            }`
}

func (g Grouping) DeleteResponseField() string { return "groupingDelete" }
