// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type MarkingDefinition struct {
	graphql.MarkingDefinition `gocti:",squash"`
}

//go:embed default_properties/marking_definition_default_properties.txt
var markingDefinitionDefaultProperties string

func (m MarkingDefinition) DefaultProperties() string {
	return markingDefinitionDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/marking_definition_list_query.txt
var markingDefinitionListQueryString string

func (m MarkingDefinition) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		markingDefinitionListQueryString,
		customAttributes,
	)
}

func (m MarkingDefinition) ListResponseField() string { return "markingDefinitions" }

// Implementing the [api.ReadableEntity] interface.

func (m MarkingDefinition) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String!) {
            markingDefinition (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (m MarkingDefinition) ReadResponseField() string { return "markingDefinition" }

// Implementing the [api.CreatableEntity] interface.

func (m MarkingDefinition) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: MarkingDefinitionAddInput!) {
            markingDefinitionAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (m MarkingDefinition) CreateResponseField() string { return "markingDefinitionAdd" }

// MarkingDefinitionAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type MarkingDefinitionAddInput struct {
	// MarkingDefinitionAddInput
	StixID           string     `gocti:"stix_id"            json:"stix_id,omitempty"`
	XOpenctiStixIDs  []string   `gocti:"x_opencti_stix_ids" json:"x_opencti_stix_ids,omitempty"`
	DefinitionType   string     `gocti:"definition_type"    json:"definition_type,omitempty"`
	Definition       string     `gocti:"definition"         json:"definition,omitempty"`
	XOpenctiOrder    int        `gocti:"x_opencti_order"    json:"x_opencti_order,omitempty"`
	XOpenctiColor    string     `gocti:"x_opencti_color"    json:"x_opencti_color,omitempty"`
	Created          *time.Time `gocti:"created"            json:"created,omitempty"`
	Modified         *time.Time `gocti:"modified"           json:"modified,omitempty"`
	ClientMutationID string     `gocti:"clientMutationId"   json:"clientMutationId,omitempty"`
	Update           bool       `gocti:"update"             json:"update,omitempty"`
}

func (input MarkingDefinitionAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (m MarkingDefinition) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                markingDefinitionEdit (id: $id) {
                    delete
                }
            }`
}

func (m MarkingDefinition) DeleteResponseField() string { return "markingDefinitionEdit" }
