// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type ThreatActor struct {
	graphql.ThreatActor `gocti:",squash"`
}

//go:embed default_properties/threat_actor_default_properties.txt
var threatActorDefaultProperties string

func (t ThreatActor) DefaultProperties() string {
	return threatActorDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/threat_actor_list_query.txt
var threatActorListQueryString string

func (t ThreatActor) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		threatActorListQueryString,
		customAttributes,
	)
}

func (t ThreatActor) ListResponseField() string { return "threatActors" }

// Implementing the [api.ReadableEntity] interface.

func (t ThreatActor) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String) {
            threatActor (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (t ThreatActor) ReadResponseField() string { return "threatActor" }
