// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type Event struct {
	graphql.Event `gocti:",squash"`
}

//go:embed default_properties/event_default_properties.txt
var eventDefaultProperties string

func (e Event) DefaultProperties() string {
	return eventDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/event_list_query.txt
var eventListQueryString string

func (e Event) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		eventListQueryString,
		customAttributes,
	)
}

func (e Event) ListResponseField() string { return "events" }

// Implementing the [api.ReadableEntity] interface.

func (e Event) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String!) {
            event (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (e Event) ReadResponseField() string { return "event" }

// Implementing the [api.CreatableEntity] interface.

func (e Event) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: EventAddInput!) {
            eventAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (e Event) CreateResponseField() string { return "eventAdd" }

// EventAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type EventAddInput struct {
	// EventAddInput
	StixID             string     `gocti:"stix_id"               json:"stix_id,omitempty"`
	XOpenctiStixIDs    []string   `gocti:"x_opencti_stix_ids"    json:"x_opencti_stix_ids,omitempty"`
	Name               string     `gocti:"name"                  json:"name,omitempty"`
	Description        string     `gocti:"description"           json:"description,omitempty"`
	EventTypes         []string   `gocti:"event_types"           json:"event_types,omitempty"`
	StartTime          *time.Time `gocti:"start_time"            json:"start_time,omitempty"`
	StopTime           *time.Time `gocti:"stop_time"             json:"stop_time,omitempty"`
	Aliases            []string   `gocti:"aliases"               json:"aliases,omitempty"`
	Confidence         int        `gocti:"confidence"            json:"confidence,omitempty"`
	Revoked            bool       `gocti:"revoked"               json:"revoked,omitempty"`
	Lang               string     `gocti:"lang"                  json:"lang,omitempty"`
	CreatedBy          string     `gocti:"createdBy"             json:"createdBy,omitempty"`
	ObjectMarking      []string   `gocti:"objectMarking"         json:"objectMarking,omitempty"`
	ObjectLabel        []string   `gocti:"objectLabel"           json:"objectLabel,omitempty"`
	ExternalReferences []string   `gocti:"externalReferences"    json:"externalReferences,omitempty"`
	Created            *time.Time `gocti:"created"               json:"created,omitempty"`
	Modified           *time.Time `gocti:"modified"              json:"modified,omitempty"`
	ClientMutationID   string     `gocti:"clientMutationId"      json:"clientMutationId,omitempty"`
	XOpenctiWorkflowID string     `gocti:"x_opencti_workflow_id" json:"x_opencti_workflow_id,omitempty"`
	Update             bool       `gocti:"update"                json:"update,omitempty"`
	File               []byte     `gocti:"file"                  json:"file,omitempty"`
}

func (input EventAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (e Event) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                eventDelete (id: $id)
            }`
}

func (e Event) DeleteResponseField() string { return "eventDelete" }
