// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type Tool struct {
	graphql.Tool `gocti:",squash"`
}

//go:embed default_properties/tool_default_properties.txt
var toolDefaultProperties string

func (t Tool) DefaultProperties() string {
	return toolDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/tool_list_query.txt
var toolListQueryString string

func (t Tool) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		toolListQueryString,
		customAttributes,
	)
}

func (t Tool) ListResponseField() string { return "tools" }

// Implementing the [api.ReadableEntity] interface.

func (t Tool) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String) {
            tool (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (t Tool) ReadResponseField() string { return "tool" }

// Implementing the [api.CreatableEntity] interface.

func (t Tool) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: ToolAddInput!) {
            toolAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (t Tool) CreateResponseField() string { return "toolAdd" }

// ToolAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type ToolAddInput struct {
	// ToolAddInput
	StixID             string     `gocti:"stix_id"               json:"stix_id,omitempty"`
	XOpenctiStixIDs    []string   `gocti:"x_opencti_stix_ids"    json:"x_opencti_stix_ids,omitempty"`
	Name               string     `gocti:"name"                  json:"name,omitempty"`
	Description        string     `gocti:"description"           json:"description,omitempty"`
	Aliases            []string   `gocti:"aliases"               json:"aliases,omitempty"`
	ToolTypes          []string   `gocti:"tool_types"            json:"tool_types,omitempty"`
	ToolVersion        string     `gocti:"tool_version"          json:"tool_version,omitempty"`
	Confidence         int        `gocti:"confidence"            json:"confidence,omitempty"`
	Revoked            bool       `gocti:"revoked"               json:"revoked,omitempty"`
	Lang               string     `gocti:"lang"                  json:"lang,omitempty"`
	CreatedBy          string     `gocti:"createdBy"             json:"createdBy,omitempty"`
	ObjectMarking      []string   `gocti:"objectMarking"         json:"objectMarking,omitempty"`
	ObjectOrganization []string   `gocti:"objectOrganization"    json:"objectOrganization,omitempty"`
	ObjectLabel        []string   `gocti:"objectLabel"           json:"objectLabel,omitempty"`
	ExternalReferences []string   `gocti:"externalReferences"    json:"externalReferences,omitempty"`
	KillChainPhases    []string   `gocti:"killChainPhases"       json:"killChainPhases,omitempty"`
	Created            *time.Time `gocti:"created"               json:"created,omitempty"`
	Modified           *time.Time `gocti:"modified"              json:"modified,omitempty"`
	XOpenctiWorkflowID string     `gocti:"x_opencti_workflow_id" json:"x_opencti_workflow_id,omitempty"`
	ClientMutationID   string     `gocti:"clientMutationId"      json:"clientMutationId,omitempty"`
	Update             bool       `gocti:"update"                json:"update,omitempty"`
	File               []byte     `gocti:"file"                  json:"file,omitempty"`
}

func (input ToolAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (t Tool) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                toolEdit (id: $id) {
                    delete
                }
            }`
}

func (t Tool) DeleteResponseField() string { return "toolEdit" }
