// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type Language struct {
	graphql.Language `gocti:",squash"`
}

//go:embed default_properties/language_default_properties.txt
var languageDefaultProperties string

func (l Language) DefaultProperties() string {
	return languageDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/language_list_query.txt
var languageListQueryString string

func (l Language) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		languageListQueryString,
		customAttributes,
	)
}

func (l Language) ListResponseField() string { return "languages" }

// Implementing the [api.ReadableEntity] interface.

func (l Language) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String!) {
            language (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (l Language) ReadResponseField() string { return "language" }

// Implementing the [api.CreatableEntity] interface.

func (l Language) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: LanguageAddInput!) {
            languageAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (l Language) CreateResponseField() string { return "languageAdd" }

// LanguageAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type LanguageAddInput struct {
	// LanguageAddInput
	StixID             string     `gocti:"stix_id"            json:"stix_id,omitempty"`
	XOpenctiStixIDs    []string   `gocti:"x_opencti_stix_ids" json:"x_opencti_stix_ids,omitempty"`
	Name               string     `gocti:"name"               json:"name,omitempty"`
	Description        string     `gocti:"description"        json:"description,omitempty"`
	Aliases            []string   `gocti:"aliases"            json:"aliases,omitempty"`
	Confidence         int        `gocti:"confidence"         json:"confidence,omitempty"`
	Revoked            bool       `gocti:"revoked"            json:"revoked,omitempty"`
	Lang               string     `gocti:"lang"               json:"lang,omitempty"`
	CreatedBy          string     `gocti:"createdBy"          json:"createdBy,omitempty"`
	ObjectMarking      []string   `gocti:"objectMarking"      json:"objectMarking,omitempty"`
	ObjectOrganization []string   `gocti:"objectOrganization" json:"objectOrganization,omitempty"`
	ObjectLabel        []string   `gocti:"objectLabel"        json:"objectLabel,omitempty"`
	ExternalReferences []string   `gocti:"externalReferences" json:"externalReferences,omitempty"`
	Created            *time.Time `gocti:"created"            json:"created,omitempty"`
	Modified           *time.Time `gocti:"modified"           json:"modified,omitempty"`
	ClientMutationID   string     `gocti:"clientMutationId"   json:"clientMutationId,omitempty"`
	Update             bool       `gocti:"update"             json:"update,omitempty"`
}

func (input LanguageAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (l Language) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                languageDelete (id: $id)
            }`
}

func (l Language) DeleteResponseField() string { return "languageDelete" }
