// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type DataSource struct {
	graphql.DataSource `gocti:",squash"`
}

//go:embed default_properties/data_source_default_properties.txt
var dataSourceDefaultProperties string

func (d DataSource) DefaultProperties() string {
	return dataSourceDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/data_source_list_query.txt
var dataSourceListQueryString string

func (d DataSource) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		dataSourceListQueryString,
		customAttributes,
	)
}

func (d DataSource) ListResponseField() string { return "dataSources" }

// Implementing the [api.ReadableEntity] interface.

func (d DataSource) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String!) {
            dataSource (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (d DataSource) ReadResponseField() string { return "dataSource" }

// Implementing the [api.CreatableEntity] interface.

func (d DataSource) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: DataSourceAddInput!) {
            dataSourceAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (d DataSource) CreateResponseField() string { return "dataSourceAdd" }

// DataSourceAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type DataSourceAddInput struct {
	// DataSourceAddInput
	StixID             string     `gocti:"stix_id"               json:"stix_id,omitempty"`
	XOpenctiStixIDs    []string   `gocti:"x_opencti_stix_ids"    json:"x_opencti_stix_ids,omitempty"`
	Confidence         int        `gocti:"confidence"            json:"confidence,omitempty"`
	Revoked            bool       `gocti:"revoked"               json:"revoked,omitempty"`
	Lang               string     `gocti:"lang"                  json:"lang,omitempty"`
	CreatedBy          string     `gocti:"createdBy"             json:"createdBy,omitempty"`
	ObjectMarking      []string   `gocti:"objectMarking"         json:"objectMarking,omitempty"`
	ObjectLabel        []string   `gocti:"objectLabel"           json:"objectLabel,omitempty"`
	ObjectOrganization []string   `gocti:"objectOrganization"    json:"objectOrganization,omitempty"`
	ExternalReferences []string   `gocti:"externalReferences"    json:"externalReferences,omitempty"`
	Created            *time.Time `gocti:"created"               json:"created,omitempty"`
	Modified           *time.Time `gocti:"modified"              json:"modified,omitempty"`
	ClientMutationID   string     `gocti:"clientMutationId"      json:"clientMutationId,omitempty"`
	Update             bool       `gocti:"update"                json:"update,omitempty"`
	Name               string     `gocti:"name"                  json:"name,omitempty"`
	Description        string     `gocti:"description"           json:"description,omitempty"`
	Aliases            []string   `gocti:"aliases"               json:"aliases,omitempty"`
	XMitrePlatforms    []string   `gocti:"x_mitre_platforms"     json:"x_mitre_platforms,omitempty"`
	CollectionLayers   []string   `gocti:"collection_layers"     json:"collection_layers,omitempty"`
	DataComponents     []string   `gocti:"dataComponents"        json:"dataComponents,omitempty"`
	File               []byte     `gocti:"file"                  json:"file,omitempty"`
	XOpenctiWorkflowID string     `gocti:"x_opencti_workflow_id" json:"x_opencti_workflow_id,omitempty"`
}

func (input DataSourceAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (d DataSource) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                dataSourceDelete (id: $id)
            }`
}

func (d DataSource) DeleteResponseField() string { return "dataSourceDelete" }
