// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type CourseOfAction struct {
	graphql.CourseOfAction `gocti:",squash"`
}

//go:embed default_properties/course_of_action_default_properties.txt
var courseOfActionDefaultProperties string

func (c CourseOfAction) DefaultProperties() string {
	return courseOfActionDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/course_of_action_list_query.txt
var courseOfActionListQueryString string

func (c CourseOfAction) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		courseOfActionListQueryString,
		customAttributes,
	)
}

func (c CourseOfAction) ListResponseField() string { return "coursesOfAction" }

// Implementing the [api.ReadableEntity] interface.

func (c CourseOfAction) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String) {
            courseOfAction (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (c CourseOfAction) ReadResponseField() string { return "courseOfAction" }

// Implementing the [api.CreatableEntity] interface.

func (c CourseOfAction) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: CourseOfActionAddInput!) {
            courseOfActionAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (c CourseOfAction) CreateResponseField() string { return "courseOfActionAdd" }

// CourseOfActionAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type CourseOfActionAddInput struct {
	// CourseOfActionAddInput
	StixID             string     `gocti:"stix_id"               json:"stix_id,omitempty"`
	XOpenctiStixIDs    []string   `gocti:"x_opencti_stix_ids"    json:"x_opencti_stix_ids,omitempty"`
	Name               string     `gocti:"name"                  json:"name,omitempty"`
	Description        string     `gocti:"description"           json:"description,omitempty"`
	XOpenctiAliases    []string   `gocti:"x_opencti_aliases"     json:"x_opencti_aliases,omitempty"`
	XMitreID           string     `gocti:"x_mitre_id"            json:"x_mitre_id,omitempty"`
	Confidence         int        `gocti:"confidence"            json:"confidence,omitempty"`
	Revoked            bool       `gocti:"revoked"               json:"revoked,omitempty"`
	Lang               string     `gocti:"lang"                  json:"lang,omitempty"`
	CreatedBy          string     `gocti:"createdBy"             json:"createdBy,omitempty"`
	ObjectMarking      []string   `gocti:"objectMarking"         json:"objectMarking,omitempty"`
	ObjectOrganization []string   `gocti:"objectOrganization"    json:"objectOrganization,omitempty"`
	ObjectLabel        []string   `gocti:"objectLabel"           json:"objectLabel,omitempty"`
	ExternalReferences []string   `gocti:"externalReferences"    json:"externalReferences,omitempty"`
	Created            *time.Time `gocti:"created"               json:"created,omitempty"`
	Modified           *time.Time `gocti:"modified"              json:"modified,omitempty"`
	XOpenctiWorkflowID string     `gocti:"x_opencti_workflow_id" json:"x_opencti_workflow_id,omitempty"`
	ClientMutationID   string     `gocti:"clientMutationId"      json:"clientMutationId,omitempty"`
	Update             bool       `gocti:"update"                json:"update,omitempty"`
	File               []byte     `gocti:"file"                  json:"file,omitempty"`
}

func (input CourseOfActionAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (c CourseOfAction) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                courseOfActionEdit (id: $id) {
                    delete
                }
            }`
}

func (c CourseOfAction) DeleteResponseField() string { return "courseOfActionEdit" }
