// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type DataComponent struct {
	graphql.DataComponent `gocti:",squash"`
}

//go:embed default_properties/data_component_default_properties.txt
var dataComponentDefaultProperties string

func (d DataComponent) DefaultProperties() string {
	return dataComponentDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/data_component_list_query.txt
var dataComponentListQueryString string

func (d DataComponent) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		dataComponentListQueryString,
		customAttributes,
	)
}

func (d DataComponent) ListResponseField() string { return "dataComponents" }

// Implementing the [api.ReadableEntity] interface.

func (d DataComponent) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String!) {
            dataComponent (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (d DataComponent) ReadResponseField() string { return "dataComponent" }

// Implementing the [api.CreatableEntity] interface.

func (d DataComponent) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: DataComponentAddInput!) {
            dataComponentAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (d DataComponent) CreateResponseField() string { return "dataComponentAdd" }

// DataComponentAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type DataComponentAddInput struct {
	// DataComponentAddInput
	StixID             string     `gocti:"stix_id"               json:"stix_id,omitempty"`
	XOpenctiStixIDs    []string   `gocti:"x_opencti_stix_ids"    json:"x_opencti_stix_ids,omitempty"`
	Confidence         int        `gocti:"confidence"            json:"confidence,omitempty"`
	Revoked            bool       `gocti:"revoked"               json:"revoked,omitempty"`
	Lang               string     `gocti:"lang"                  json:"lang,omitempty"`
	CreatedBy          string     `gocti:"createdBy"             json:"createdBy,omitempty"`
	ObjectMarking      []string   `gocti:"objectMarking"         json:"objectMarking,omitempty"`
	ObjectLabel        []string   `gocti:"objectLabel"           json:"objectLabel,omitempty"`
	ObjectOrganization []string   `gocti:"objectOrganization"    json:"objectOrganization,omitempty"`
	ExternalReferences []string   `gocti:"externalReferences"    json:"externalReferences,omitempty"`
	Created            *time.Time `gocti:"created"               json:"created,omitempty"`
	Modified           *time.Time `gocti:"modified"              json:"modified,omitempty"`
	ClientMutationID   string     `gocti:"clientMutationId"      json:"clientMutationId,omitempty"`
	Update             bool       `gocti:"update"                json:"update,omitempty"`
	Name               string     `gocti:"name"                  json:"name,omitempty"`
	Description        string     `gocti:"description"           json:"description,omitempty"`
	Aliases            []string   `gocti:"aliases"               json:"aliases,omitempty"`
	DataSource         string     `gocti:"dataSource"            json:"dataSource,omitempty"`
	File               []byte     `gocti:"file"                  json:"file,omitempty"`
	XOpenctiWorkflowID string     `gocti:"x_opencti_workflow_id" json:"x_opencti_workflow_id,omitempty"`
}

func (input DataComponentAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (d DataComponent) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                dataComponentDelete (id: $id)
            }`
}

func (d DataComponent) DeleteResponseField() string { return "dataComponentDelete" }
