// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type StixCoreObject struct {
	graphql.StixCoreObject `gocti:",squash"`
}

//go:embed default_properties/stix_core_object_default_properties.txt
var stixCoreObjectDefaultProperties string

func (s StixCoreObject) DefaultProperties() string {
	return stixCoreObjectDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/stix_core_object_list_query.txt
var stixCoreObjectListQueryString string

func (s StixCoreObject) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		stixCoreObjectListQueryString,
		customAttributes,
	)
}

func (s StixCoreObject) ListResponseField() string { return "stixCoreObjects" }

// Implementing the [api.ReadableEntity] interface.

func (s StixCoreObject) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String!) {
            stixCoreObject (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (s StixCoreObject) ReadResponseField() string { return "stixCoreObject" }

// Implementing the [api.DeletableEntity] interface.

func (s StixCoreObject) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                stixCoreObjectEdit (id: $id) {
                    delete
                }
            }`
}

func (s StixCoreObject) DeleteResponseField() string { return "stixCoreObjectEdit" }
