// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type ThreatActorGroup struct {
	graphql.ThreatActorGroup `gocti:",squash"`
}

//go:embed default_properties/threat_actor_group_default_properties.txt
var threatActorGroupDefaultProperties string

func (t ThreatActorGroup) DefaultProperties() string {
	return threatActorGroupDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/threat_actor_group_list_query.txt
var threatActorGroupListQueryString string

func (t ThreatActorGroup) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		threatActorGroupListQueryString,
		customAttributes,
	)
}

func (t ThreatActorGroup) ListResponseField() string { return "threatActorsGroup" }

// Implementing the [api.ReadableEntity] interface.

func (t ThreatActorGroup) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String) {
            threatActorGroup (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (t ThreatActorGroup) ReadResponseField() string { return "threatActorGroup" }

// Implementing the [api.CreatableEntity] interface.

func (t ThreatActorGroup) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: ThreatActorGroupAddInput!) {
            threatActorGroupAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (t ThreatActorGroup) CreateResponseField() string { return "threatActorGroupAdd" }

// ThreatActorGroupAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type ThreatActorGroupAddInput struct {
	// ThreatActorGroupAddInput
	StixID               string     `gocti:"stix_id"               json:"stix_id,omitempty"`
	XOpenctiStixIDs      []string   `gocti:"x_opencti_stix_ids"    json:"x_opencti_stix_ids,omitempty"`
	Name                 string     `gocti:"name"                  json:"name,omitempty"`
	Description          string     `gocti:"description"           json:"description,omitempty"`
	Aliases              []string   `gocti:"aliases"               json:"aliases,omitempty"`
	ThreatActorTypes     []string   `gocti:"threat_actor_types"    json:"threat_actor_types,omitempty"`
	FirstSeen            *time.Time `gocti:"first_seen"            json:"first_seen,omitempty"`
	LastSeen             *time.Time `gocti:"last_seen"             json:"last_seen,omitempty"`
	Roles                []string   `gocti:"roles"                 json:"roles,omitempty"`
	Goals                []string   `gocti:"goals"                 json:"goals,omitempty"`
	Sophistication       string     `gocti:"sophistication"        json:"sophistication,omitempty"`
	ResourceLevel        string     `gocti:"resource_level"        json:"resource_level,omitempty"`
	PrimaryMotivation    string     `gocti:"primary_motivation"    json:"primary_motivation,omitempty"`
	SecondaryMotivations []string   `gocti:"secondary_motivations" json:"secondary_motivations,omitempty"`
	PersonalMotivations  []string   `gocti:"personal_motivations"  json:"personal_motivations,omitempty"`
	Confidence           int        `gocti:"confidence"            json:"confidence,omitempty"`
	Revoked              bool       `gocti:"revoked"               json:"revoked,omitempty"`
	Lang                 string     `gocti:"lang"                  json:"lang,omitempty"`
	CreatedBy            string     `gocti:"createdBy"             json:"createdBy,omitempty"`
	ObjectMarking        []string   `gocti:"objectMarking"         json:"objectMarking,omitempty"`
	ObjectOrganization   []string   `gocti:"objectOrganization"    json:"objectOrganization,omitempty"`
	ObjectAssignee       []string   `gocti:"objectAssignee"        json:"objectAssignee,omitempty"`
	ObjectLabel          []string   `gocti:"objectLabel"           json:"objectLabel,omitempty"`
	ExternalReferences   []string   `gocti:"externalReferences"    json:"externalReferences,omitempty"`
	Created              *time.Time `gocti:"created"               json:"created,omitempty"`
	Modified             *time.Time `gocti:"modified"              json:"modified,omitempty"`
	XOpenctiWorkflowID   string     `gocti:"x_opencti_workflow_id" json:"x_opencti_workflow_id,omitempty"`
	ClientMutationID     string     `gocti:"clientMutationId"      json:"clientMutationId,omitempty"`
	Update               bool       `gocti:"update"                json:"update,omitempty"`
	File                 []byte     `gocti:"file"                  json:"file,omitempty"`
}

func (input ThreatActorGroupAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (t ThreatActorGroup) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                threatActorGroupEdit (id: $id) {
                    delete
                }
            }`
}

func (t ThreatActorGroup) DeleteResponseField() string { return "threatActorGroupEdit" }
