// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type AttackPattern struct {
	graphql.AttackPattern `gocti:",squash"`
}

//go:embed default_properties/attack_pattern_default_properties.txt
var attackPatternDefaultProperties string

func (a AttackPattern) DefaultProperties() string {
	return attackPatternDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/attack_pattern_list_query.txt
var attackPatternListQueryString string

func (a AttackPattern) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		attackPatternListQueryString,
		customAttributes,
	)
}

func (a AttackPattern) ListResponseField() string { return "attackPatterns" }

// Implementing the [api.ReadableEntity] interface.

func (a AttackPattern) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String) {
            attackPattern (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (a AttackPattern) ReadResponseField() string { return "attackPattern" }

// Implementing the [api.CreatableEntity] interface.

func (a AttackPattern) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: AttackPatternAddInput!) {
            attackPatternAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (a AttackPattern) CreateResponseField() string { return "attackPatternAdd" }

// AttackPatternAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type AttackPatternAddInput struct {
	// AttackPatternAddInput
	StixID                    string     `gocti:"stix_id"                      json:"stix_id,omitempty"`
	XOpenctiStixIDs           []string   `gocti:"x_opencti_stix_ids"           json:"x_opencti_stix_ids,omitempty"`
	Name                      string     `gocti:"name"                         json:"name,omitempty"`
	Description               string     `gocti:"description"                  json:"description,omitempty"`
	Aliases                   []string   `gocti:"aliases"                      json:"aliases,omitempty"`
	Revoked                   bool       `gocti:"revoked"                      json:"revoked,omitempty"`
	Lang                      string     `gocti:"lang"                         json:"lang,omitempty"`
	Confidence                int        `gocti:"confidence"                   json:"confidence,omitempty"`
	XMitrePlatforms           []string   `gocti:"x_mitre_platforms"            json:"x_mitre_platforms,omitempty"`
	XMitrePermissionsRequired []string   `gocti:"x_mitre_permissions_required" json:"x_mitre_permissions_required,omitempty"`
	XMitreDetection           string     `gocti:"x_mitre_detection"            json:"x_mitre_detection,omitempty"`
	XMitreID                  string     `gocti:"x_mitre_id"                   json:"x_mitre_id,omitempty"`
	CreatedBy                 string     `gocti:"createdBy"                    json:"createdBy,omitempty"`
	ObjectMarking             []string   `gocti:"objectMarking"                json:"objectMarking,omitempty"`
	ObjectOrganization        []string   `gocti:"objectOrganization"           json:"objectOrganization,omitempty"`
	ObjectLabel               []string   `gocti:"objectLabel"                  json:"objectLabel,omitempty"`
	KillChainPhases           []string   `gocti:"killChainPhases"              json:"killChainPhases,omitempty"`
	ExternalReferences        []string   `gocti:"externalReferences"           json:"externalReferences,omitempty"`
	Created                   *time.Time `gocti:"created"                      json:"created,omitempty"`
	Modified                  *time.Time `gocti:"modified"                     json:"modified,omitempty"`
	XOpenctiWorkflowID        string     `gocti:"x_opencti_workflow_id"        json:"x_opencti_workflow_id,omitempty"`
	ClientMutationID          string     `gocti:"clientMutationId"             json:"clientMutationId,omitempty"`
	Update                    bool       `gocti:"update"                       json:"update,omitempty"`
	File                      []byte     `gocti:"file"                         json:"file,omitempty"`
}

func (input AttackPatternAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (a AttackPattern) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                attackPatternEdit (id: $id) {
                    delete
                }
            }`
}

func (a AttackPattern) DeleteResponseField() string { return "attackPatternEdit" }
