// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type Campaign struct {
	graphql.Campaign `gocti:",squash"`
}

//go:embed default_properties/campaign_default_properties.txt
var campaignDefaultProperties string

func (c Campaign) DefaultProperties() string {
	return campaignDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/campaign_list_query.txt
var campaignListQueryString string

func (c Campaign) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		campaignListQueryString,
		customAttributes,
	)
}

func (c Campaign) ListResponseField() string { return "campaigns" }

// Implementing the [api.ReadableEntity] interface.

func (c Campaign) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String) {
            campaign (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (c Campaign) ReadResponseField() string { return "campaign" }

// Implementing the [api.CreatableEntity] interface.

func (c Campaign) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: CampaignAddInput!) {
            campaignAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (c Campaign) CreateResponseField() string { return "campaignAdd" }

// CampaignAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type CampaignAddInput struct {
	// CampaignAddInput
	StixID             string     `gocti:"stix_id"               json:"stix_id,omitempty"`
	XOpenctiStixIDs    []string   `gocti:"x_opencti_stix_ids"    json:"x_opencti_stix_ids,omitempty"`
	Name               string     `gocti:"name"                  json:"name,omitempty"`
	Description        string     `gocti:"description"           json:"description,omitempty"`
	Aliases            []string   `gocti:"aliases"               json:"aliases,omitempty"`
	Revoked            bool       `gocti:"revoked"               json:"revoked,omitempty"`
	Lang               string     `gocti:"lang"                  json:"lang,omitempty"`
	Confidence         int        `gocti:"confidence"            json:"confidence,omitempty"`
	FirstSeen          *time.Time `gocti:"first_seen"            json:"first_seen,omitempty"`
	LastSeen           *time.Time `gocti:"last_seen"             json:"last_seen,omitempty"`
	Objective          string     `gocti:"objective"             json:"objective,omitempty"`
	CreatedBy          string     `gocti:"createdBy"             json:"createdBy,omitempty"`
	ObjectMarking      []string   `gocti:"objectMarking"         json:"objectMarking,omitempty"`
	ObjectAssignee     []string   `gocti:"objectAssignee"        json:"objectAssignee,omitempty"`
	ObjectOrganization []string   `gocti:"objectOrganization"    json:"objectOrganization,omitempty"`
	ObjectLabel        []string   `gocti:"objectLabel"           json:"objectLabel,omitempty"`
	ExternalReferences []string   `gocti:"externalReferences"    json:"externalReferences,omitempty"`
	Created            *time.Time `gocti:"created"               json:"created,omitempty"`
	Modified           *time.Time `gocti:"modified"              json:"modified,omitempty"`
	XOpenctiWorkflowID string     `gocti:"x_opencti_workflow_id" json:"x_opencti_workflow_id,omitempty"`
	ClientMutationID   string     `gocti:"clientMutationId"      json:"clientMutationId,omitempty"`
	Update             bool       `gocti:"update"                json:"update,omitempty"`
	File               []byte     `gocti:"file"                  json:"file,omitempty"`
}

func (input CampaignAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (c Campaign) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                campaignEdit (id: $id) {
                    delete
                }
            }`
}

func (c Campaign) DeleteResponseField() string { return "campaignEdit" }
