// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type Channel struct {
	graphql.Channel `gocti:",squash"`
}

//go:embed default_properties/channel_default_properties.txt
var channelDefaultProperties string

func (c Channel) DefaultProperties() string {
	return channelDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/channel_list_query.txt
var channelListQueryString string

func (c Channel) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		channelListQueryString,
		customAttributes,
	)
}

func (c Channel) ListResponseField() string { return "channels" }

// Implementing the [api.ReadableEntity] interface.

func (c Channel) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String!) {
            channel (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (c Channel) ReadResponseField() string { return "channel" }

// Implementing the [api.CreatableEntity] interface.

func (c Channel) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: ChannelAddInput!) {
            channelAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (c Channel) CreateResponseField() string { return "channelAdd" }

// ChannelAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type ChannelAddInput struct {
	// ChannelAddInput
	StixID             string     `gocti:"stix_id"               json:"stix_id,omitempty"`
	XOpenctiStixIDs    []string   `gocti:"x_opencti_stix_ids"    json:"x_opencti_stix_ids,omitempty"`
	Name               string     `gocti:"name"                  json:"name,omitempty"`
	Description        string     `gocti:"description"           json:"description,omitempty"`
	ChannelTypes       []string   `gocti:"channel_types"         json:"channel_types,omitempty"`
	Aliases            []string   `gocti:"aliases"               json:"aliases,omitempty"`
	Confidence         int        `gocti:"confidence"            json:"confidence,omitempty"`
	Revoked            bool       `gocti:"revoked"               json:"revoked,omitempty"`
	Lang               string     `gocti:"lang"                  json:"lang,omitempty"`
	CreatedBy          string     `gocti:"createdBy"             json:"createdBy,omitempty"`
	ObjectMarking      []string   `gocti:"objectMarking"         json:"objectMarking,omitempty"`
	ObjectOrganization []string   `gocti:"objectOrganization"    json:"objectOrganization,omitempty"`
	ObjectLabel        []string   `gocti:"objectLabel"           json:"objectLabel,omitempty"`
	ExternalReferences []string   `gocti:"externalReferences"    json:"externalReferences,omitempty"`
	Created            *time.Time `gocti:"created"               json:"created,omitempty"`
	Modified           *time.Time `gocti:"modified"              json:"modified,omitempty"`
	XOpenctiWorkflowID string     `gocti:"x_opencti_workflow_id" json:"x_opencti_workflow_id,omitempty"`
	ClientMutationID   string     `gocti:"clientMutationId"      json:"clientMutationId,omitempty"`
	Update             bool       `gocti:"update"                json:"update,omitempty"`
	File               []byte     `gocti:"file"                  json:"file,omitempty"`
}

func (input ChannelAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (c Channel) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                channelDelete (id: $id)
            }`
}

func (c Channel) DeleteResponseField() string { return "channelDelete" }
