// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type StixCoreRelationship struct {
	graphql.StixCoreRelationship `gocti:",squash"`
}

//go:embed default_properties/stix_core_relationship_default_properties.txt
var stixCoreRelationshipDefaultProperties string

func (s StixCoreRelationship) DefaultProperties() string {
	return stixCoreRelationshipDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/stix_core_relationship_list_query.txt
var stixCoreRelationshipListQueryString string

func (s StixCoreRelationship) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		stixCoreRelationshipListQueryString,
		customAttributes,
	)
}

func (s StixCoreRelationship) ListResponseField() string { return "stixCoreRelationships" }

// Implementing the [api.ReadableEntity] interface.

func (s StixCoreRelationship) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String) {
            stixCoreRelationship (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (s StixCoreRelationship) ReadResponseField() string { return "stixCoreRelationship" }

// Implementing the [api.CreatableEntity] interface.

func (s StixCoreRelationship) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: StixCoreRelationshipAddInput
                  $reversedReturn: Boolean) {
            stixCoreRelationshipAdd (input: $input
                                     reversedReturn: $reversedReturn) {%s}
        }`,
		customAttributes,
	)
}

func (s StixCoreRelationship) CreateResponseField() string { return "stixCoreRelationshipAdd" }

// StixCoreRelationshipAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type StixCoreRelationshipAddInput struct {
	// StixCoreRelationshipAddInput
	StixID             string     `gocti:"stix_id"               json:"stix_id,omitempty"`
	XOpenctiStixIDs    []string   `gocti:"x_opencti_stix_ids"    json:"x_opencti_stix_ids,omitempty"`
	FromID             string     `gocti:"fromId"                json:"fromId,omitempty"`
	ToID               string     `gocti:"toId"                  json:"toId,omitempty"`
	Created            *time.Time `gocti:"created"               json:"created,omitempty"`
	Modified           *time.Time `gocti:"modified"              json:"modified,omitempty"`
	Confidence         int        `gocti:"confidence"            json:"confidence,omitempty"`
	RelationshipType   string     `gocti:"relationship_type"     json:"relationship_type,omitempty"`
	CreatedBy          string     `gocti:"createdBy"             json:"createdBy,omitempty"`
	ObjectMarking      []string   `gocti:"objectMarking"         json:"objectMarking,omitempty"`
	Description        string     `gocti:"description"           json:"description,omitempty"`
	StartTime          *time.Time `gocti:"start_time"            json:"start_time,omitempty"`
	StopTime           *time.Time `gocti:"stop_time"             json:"stop_time,omitempty"`
	Revoked            bool       `gocti:"revoked"               json:"revoked,omitempty"`
	Lang               string     `gocti:"lang"                  json:"lang,omitempty"`
	ObjectLabel        []string   `gocti:"objectLabel"           json:"objectLabel,omitempty"`
	ObjectOrganization []string   `gocti:"objectOrganization"    json:"objectOrganization,omitempty"`
	ExternalReferences []string   `gocti:"externalReferences"    json:"externalReferences,omitempty"`
	KillChainPhases    []string   `gocti:"killChainPhases"       json:"killChainPhases,omitempty"`
	XOpenctiWorkflowID string     `gocti:"x_opencti_workflow_id" json:"x_opencti_workflow_id,omitempty"`
	ClientMutationID   string     `gocti:"clientMutationId"      json:"clientMutationId,omitempty"`
	Update             bool       `gocti:"update"                json:"update,omitempty"`

	// Custom
	ReversedReturn bool `gocti:"-" json:"-,omitempty"`
}

func (input StixCoreRelationshipAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input":          input,
		"reversedReturn": input.ReversedReturn,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (s StixCoreRelationship) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                stixCoreRelationshipEdit (id: $id) {
                    delete
                }
            }`
}

func (s StixCoreRelationship) DeleteResponseField() string { return "stixCoreRelationshipEdit" }
