// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package entity

import (
	"fmt"
	"time"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type ObservedData struct {
	graphql.ObservedData `gocti:",squash"`
}

//go:embed default_properties/observed_data_default_properties.txt
var observedDataDefaultProperties string

func (o ObservedData) DefaultProperties() string {
	return observedDataDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/observed_data_list_query.txt
var observedDataListQueryString string

func (o ObservedData) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		observedDataListQueryString,
		customAttributes,
	)
}

func (o ObservedData) ListResponseField() string { return "observedDatas" }

// Implementing the [api.ReadableEntity] interface.

func (o ObservedData) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String) {
            observedData (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (o ObservedData) ReadResponseField() string { return "observedData" }

// Implementing the [api.CreatableEntity] interface.

func (o ObservedData) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: ObservedDataAddInput!) {
            observedDataAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (o ObservedData) CreateResponseField() string { return "observedDataAdd" }

// ObservedDataAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type ObservedDataAddInput struct {
	// ObservedDataAddInput
	StixID             string     `gocti:"stix_id"               json:"stix_id,omitempty"`
	XOpenctiStixIDs    []string   `gocti:"x_opencti_stix_ids"    json:"x_opencti_stix_ids,omitempty"`
	FirstObserved      *time.Time `gocti:"first_observed"        json:"first_observed,omitempty"`
	LastObserved       *time.Time `gocti:"last_observed"         json:"last_observed,omitempty"`
	NumberObserved     int        `gocti:"number_observed"       json:"number_observed,omitempty"`
	Revoked            bool       `gocti:"revoked"               json:"revoked,omitempty"`
	Lang               string     `gocti:"lang"                  json:"lang,omitempty"`
	Confidence         int        `gocti:"confidence"            json:"confidence,omitempty"`
	CreatedBy          string     `gocti:"createdBy"             json:"createdBy,omitempty"`
	ObjectMarking      []string   `gocti:"objectMarking"         json:"objectMarking,omitempty"`
	ObjectLabel        []string   `gocti:"objectLabel"           json:"objectLabel,omitempty"`
	ObjectOrganization []string   `gocti:"objectOrganization"    json:"objectOrganization,omitempty"`
	ExternalReferences []string   `gocti:"externalReferences"    json:"externalReferences,omitempty"`
	Objects            []string   `gocti:"objects"               json:"objects,omitempty"`
	Created            *time.Time `gocti:"created"               json:"created,omitempty"`
	Modified           *time.Time `gocti:"modified"              json:"modified,omitempty"`
	XOpenctiWorkflowID string     `gocti:"x_opencti_workflow_id" json:"x_opencti_workflow_id,omitempty"`
	ClientMutationID   string     `gocti:"clientMutationId"      json:"clientMutationId,omitempty"`
	Update             bool       `gocti:"update"                json:"update,omitempty"`
	File               []byte     `gocti:"file"                  json:"file,omitempty"`
}

func (input ObservedDataAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (o ObservedData) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                observedDataEdit (id: $id) {
                    delete
                }
            }`
}

func (o ObservedData) DeleteResponseField() string { return "observedDataEdit" }
