// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package system

import (
	"fmt"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type Capability struct {
	graphql.Capability `gocti:",squash"`
}

//go:embed default_properties/capability_default_properties.txt
var capabilityDefaultProperties string

func (c Capability) DefaultProperties() string {
	return capabilityDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/capability_list_query.txt
var capabilityListQueryString string

func (c Capability) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		capabilityListQueryString,
		customAttributes,
	)
}

func (c Capability) ListResponseField() string { return "capabilities" }
