// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package system

import (
	"fmt"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type SubType struct {
	graphql.SubType `gocti:",squash"`
}

//go:embed default_properties/sub_type_default_properties.txt
var subTypeDefaultProperties string

func (s SubType) DefaultProperties() string {
	return subTypeDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/sub_type_list_query.txt
var subTypeListQueryString string

func (s SubType) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		subTypeListQueryString,
		customAttributes,
	)
}

func (s SubType) ListResponseField() string { return "subTypes" }

// Implementing the [api.ReadableEntity] interface.

func (s SubType) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String!) {
            subType (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (s SubType) ReadResponseField() string { return "subType" }

// Implementing the [api.DeletableEntity] interface.

func (s SubType) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                subTypeEdit (id: $id) {
                    delete
                }
            }`
}

func (s SubType) DeleteResponseField() string { return "subTypeEdit" }
