// Code generated by '/tools/gocti_type_generator' for OpenCTI version 6.7.12 - DO NOT EDIT.

package system

import (
	"fmt"

	"github.com/weisshorn-cyd/gocti/graphql"

	_ "embed"
)

type Group struct {
	graphql.Group `gocti:",squash"`
}

//go:embed default_properties/group_default_properties.txt
var groupDefaultProperties string

func (g Group) DefaultProperties() string {
	return groupDefaultProperties
}

// Implementing the [api.ListableEntity] interface.

//go:embed list_queries/group_list_query.txt
var groupListQueryString string

func (g Group) ListQueryString(customAttributes string) string {
	return fmt.Sprintf(
		groupListQueryString,
		customAttributes,
	)
}

func (g Group) ListResponseField() string { return "groups" }

// Implementing the [api.ReadableEntity] interface.

func (g Group) ReadQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`query ($id: String!) {
            group (id: $id) {%s}
        }`,
		customAttributes,
	)
}

func (g Group) ReadResponseField() string { return "group" }

// Implementing the [api.CreatableEntity] interface.

func (g Group) CreateQueryString(customAttributes string) string {
	return fmt.Sprintf(
		`mutation ($input: GroupAddInput!) {
            groupAdd (input: $input) {%s}
        }`,
		customAttributes,
	)
}

func (g Group) CreateResponseField() string { return "groupAdd" }

// GroupAddInput represents a GraphQL INPUT_OBJECT
// Some fields from the OpenCTI schema may be missing
// (See the examples for ways to expand an existing type).
type GroupAddInput struct {
	// GroupAddInput
	Name                 string                       `gocti:"name"                   json:"name,omitempty"`
	Description          string                       `gocti:"description"            json:"description,omitempty"`
	DefaultAssignation   bool                         `gocti:"default_assignation"    json:"default_assignation,omitempty"`
	NoCreators           bool                         `gocti:"no_creators"            json:"no_creators,omitempty"`
	RestrictDelete       bool                         `gocti:"restrict_delete"        json:"restrict_delete,omitempty"`
	AutoNewMarking       bool                         `gocti:"auto_new_marking"       json:"auto_new_marking,omitempty"`
	ClientMutationID     string                       `gocti:"clientMutationId"       json:"clientMutationId,omitempty"`
	GroupConfidenceLevel graphql.ConfidenceLevelInput `gocti:"group_confidence_level" json:"group_confidence_level,omitempty"`
}

func (input GroupAddInput) Input() (map[string]any, error) {
	return map[string]any{
		"input": input,
	}, nil
}

// Implementing the [api.DeletableEntity] interface.

func (g Group) DeleteQueryString() string {
	return `mutation ($id: ID!) {
                groupEdit (id: $id) {
                    delete
                }
            }`
}

func (g Group) DeleteResponseField() string { return "groupEdit" }
