name: python
on:
  push:
    branches:
      - master
      - main
  pull_request:
    paths:
      - '**.py'
      - '**pyproject.toml'

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
      - run: ruff check
