name: python
on:
  push:
    branches:
      - master
      - main
  pull_request:
    paths:
      - '**.py'
      - '**pyproject.toml'

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/ruff-action@v9828f49eb4cadf267b40eaa330295c412c68c1f9 # v3.2.2
        with:
          args: "format --check"
      - run: ruff check
